version: '3'
services:
  web:
    image: "mordhau/eth-web"
    ports:
      - 80:3001
    depends_on:
      - redis
      - geth
      - data
  data:
      image: "mordhau/eth-data"
      ports:
        - 3000:3000
      depends_on:
        - redis
        - geth
  redis:
    image: "redis:alpine"
  geth:
    image: "mordhau/ethereum-geth-dev"
    volumes:
      - blockchain:/app/blockchain
    ports:
      - 30303:30303
      - 8545:8545
volumes:
  blockchain: