version: '3'
services:
  web:
    build: ./web
    command: npm run dev
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - geth
      - data
    volumes:
      - ./web:/app
      - /app/node_modules
  data:
      build: ./data
      command: npm run dev
      ports:
        - "3000:3000"
      depends_on:
        - redis
        - geth
      volumes:
        - ./data:/app
        - /app/node_modules
  redis:
    image: "redis:alpine"
  geth:
    image: "mordhau/ethereum-geth-dev"
    ports:
     - 30303:30303
     - 8545:8545