version: '3'
services:
  web:
    build: .
    command: npm run dev
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - geth
    volumes:
      - .:/app
  redis:
    image: "redis:alpine"
  geth:
    image: "makevoid/ethereum-geth-dev"
    ports:
     - 30303:30303
     - 8545:8545